### ISSUE TITLE
Demisexual sexual orientation

### ISSUE THREAD

**Issue by Biska** [fetlife/glossary#14]
A demisexual is a person who does not experience sexual attraction unless they form a strong emotional connection with someone.

**Comment by warlenexus** [comment]
In the demi vein, there's also demigirl, demifemale, demilady, demiboy, demimale, demiman. It means partially identifying as a male or female, while retaining celebration of the genitals you're born with.

**Comment by APTememe** [comment]
Crumbs

**Comment by johnbaku** [comment]
I've written feature spec to add `Demisexual` as a sexual orientation. Once an engineer frees up sometime, it will be added.

For my reference:
https://github.com/fetlife/guidelines/issues/355

*P.S. Once it's been added to FetLife we will come back here to announce it and close the issue so that everyone know. *

**Comment by nielsenramon** [comment]
You can now add Demisexual as a sexual orientation!
